apiVersion: kuberest.solidite.fr/v1
kind: RestEndPoint
metadata:
  name: password-generator
spec:
  inputs:
  - name: output
    secretRef:
      optional: true
      name: output
  - name: password
    passwordGenerator: {}
  - name: weak
    passwordGenerator:
      length: 8
      weightSymbols: 0
  - name: hbsweak
    handleBarsRender: "{{ gen_password_alphanum 8 }}"
  - name: hbspassword
    handleBarsRender: "{{ gen_password 32 }}"
  templates:
  - name: password
    template: >-
      {{#if input.output.data.password }}{{ base64_decode input.output.data.password }}{{else}}{{ input.password }}{{/if}}
  client:
    baseurl: "http://localhost:8080"
  outputs:
  - kind: Secret
    metadata:
      name: output
    data:
      password: "{{> password }}"
      weak: "{{ input.weak }}"
      hbsweak: "{{ input.hbsweak }}"
      hbspassword: "{{ input.hbspassword }}"
