apiVersion: kuberest.solidite.fr/v1
kind: RestEndPoint
metadata:
  name: secret-copy
spec:
  checkFrequency: 900
  inputs:
  - name: token
    secretRef:
      name: copied-from
      namespace: source-namespace
  client:
    baseurl: "http://localhost:8080"
  outputs:
  - kind: Secret
    metadata:
      name: copied-to
      namespace: destination-namespace
    data:
      gitlab_token: "{{ base64_decode input.token.data.gitlab_token }}"
