apiVersion: kuberest.solidite.fr/v1
kind: RestEndPoint
metadata:
  name: dataout
spec:
  inputs:
  - name: cfg
    configMapRef:
      name: some-cfg
  - name: secret
    secretRef:
      name: some-secret
  client:
    baseurl: "https://gitlab.your-company.com/api/v4"
    headers:
      Authorization: "Basic {{ data.secret.username+':'+data.secret.password | base64encode }}"
      Content-Type: "application/json; charset=utf-8"
      Accept: application/json
  reads:
  - name: test
    path: "project"
    items:
    - name: test
      key: "34"
  writes:
  - name: project
    path: projects
    items:
    - name: test
      inputs:
        prout: enia
        name: test

  outputs:
  - kind: Secret
    metadata:
      name: some-other-secret
    stringData:
      client-id: "{{ paths.project.items.test.client-id }}"
  - kind: ConfigMap
    metadata:
      name: some-other-cm
    data:
      client-name: "{{ paths.project.items.test.name }}"
